### ISSUE TITLE
Explicit usage of ppc-amigaos-strip should be avoided to allow overriding by upstream build tool chains

### ISSUE THREAD

**Issue by 3246251196** [afxgroup/clib2#142]
https://github.com/afxgroup/clib2/blob/28aa4eec565160d7fbe90cd534fc57542d921d65/GNUmakefile.os4#L205

While trying to build a native compiler, I came across a situation where one of the rules in CLIB2 was explicitly using **ppc-amigaos-strip**. Instead, by setting that as a variable - as is already done for CC, AR, LD and RANLIB - it allows the overriding of its value.

The request is to set a variable in the makefile:
`STRIP=ppc-amigaos-strip
`
and use $(STRIP) instead.

===

Reason: Firstly, it is more consistent this way. Other BINs like CC, AR use variables. Secondly, when building ADTOOLS the locations of those binaries may not yet be on the path - in the ADTOOLS makefile there are things like:

CC=/path/to/Xcompiler/bin/ppc-amigaos-gcc
and then CC is fed into CLIB2. This does not happen for STRIP, so it causes a failure.

===

Request to merge into BETA10, which should finally propagate through to MASTER.

**Comment by 3246251196** [comment]
See: #143

**Comment by afxgroup** [comment]
In beta10
