### ISSUE TITLE
Makefile's install rule should also copy "clib2.library" to INSTALL_PREFIX

### ISSUE THREAD

**Issue by 3246251196** [afxgroup/clib2#145]
Question: Whether to consider copying "clib2.library" to as part of the "install" Makefile rule to $(INSTALL_PREFIX).

It is not an unlikely event that someone would create a cross-compiler, install it and throw away the downloaded clib2 repository. That would result in throwing away the Shared Library.

Of course, there is no "libs" directory in the SDK, but maybe we can copy it somewhere...

Just an inconvenience.

**Comment by afxgroup** [comment]
I'll copy it into INSTALL_PREFIX. There are no other common places where to put it.

**Comment by afxgroup** [comment]
in beta10
