### ISSUE TITLE
Porting and Sys/Wait.h

### ISSUE THREAD

**Issue by 3246251196** [afxgroup/clib2#146]
In the context of porting, a **configure** step often involves a check to see if there exists a _POSIX wait.h_. In CLIB2, there is. The configure test generally just includes **sys/wait.h** and attempts to ensure that it can link having invoked the **wait** function. This trickles down to assumptions during a build of a port because the definition **HAVE_SYS_WAIT_H** is set to **1**. Later on, there may be undefined references to things like **waitpid**.

I wonder if there is a possibility to add in some macro that can be enabled in CPPFLAGS so that during the configure step (or, indeed, during any step), CLIB2's wait does not exist.

At the moment, I am not sure that is a good idea. I just wanted to point out a situation that occurs.

**Comment by afxgroup** [comment]
I don't think so. You have to deal with it.. and add in the code some #ifdefs around waitpid/fork functions. Keep in mind that most of the time that kind of software will not work on OS4. No matter if you have or not sys/wait.h. Except if in the code they provide something different. Luckily the new software has replaced fork with pthreads

**Comment by 3246251196** [comment]
Right. I expected that response and agree.
