### ISSUE TITLE
Major issues with makefile.

### ISSUE THREAD

**Issue by kas1e** [afxgroup/clib2#26]
I tried to build this clib2 like "make -f GNUMakefile.os4", and have immediately those kind of errors:

```
user@DESKTOP-3NFAB0O /amiga2/clib2-master
$ make -f GNUmakefile.os4
Assembling \033[0;33m[build/lib]\033[0m \r\t\t\t\t\t\t\t\t \033[0;31mcrt0.o\033[0m
cp -r ./build/lib/crt0.o /usr/ppc-amigaos/SDK/clib2/lib/
cp: cannot create regular file '/usr/ppc-amigaos/SDK/clib2/lib/': No such file or directory
make: *** [GNUmakefile.os4:154: build/lib/crt0.o] Error 1
```

IMHO, if anyone run makefile without any options, it should doing just that : only compile code. No install, not "cp -r build", etc. Pure complation of files and libs. Then if anyone wish can use "make install" or whatever. As it now it looks strange, why it tried to copy anything without being asked for , it should compile code imho :)

So my suggestion is that makefile need to be structured like this : firstly everything compiles in its own build directory, and only then, if one do "make install" copy the things. As of now it looks like it tries to compile something , and then immediately copy.

To add , Makefile also have some hardcore patches like INSTALL_PREFIX = /usr/ppc-amigaos/SDK/clib2 and SDK_INCLUDE := /usr/ppc-amigaos/SDK/include, while most of time by default it's /usr/local/amiga/ppc-amigaos. But anyway there should't be any hardcore stuff, but probabaly after compilation done, should be something like "make install /usr/albaklalasd/ppc-amigaos/" etc.

To summorize as i see it and what we need to do:

1. Make makefile to only compile code when run pure "make -f Makefile". No COPY should be done.
2. When we compile everything, we can install it by something like "make install", but also we should provide a path to our SDK, so it will be like ```make install /usr/local/amiga/ppc-amigaos/SDK```

**Comment by afxgroup** [comment]
copy is needed if you want to compile GCC an no clib2 exists in the system. If you don't copy the files once created the GCC compilation will fail.
In your case the problem is that the path doesn't exists because is different. If we hardcode the paths there is no other way to use a standard path or maybe use some export variables and then test against them.
If you change the path in the makefile to point to your SDK everything will be ok.
So maybe we can test against SDK or PREFIX. What do you think?

**Comment by kas1e** [comment]
>  copy is needed if you want to compile GCC an no clib2 exists in the system. If you don't copy the files once created the GCC compilation will fail.

What  mean is that it copy things in the process : not after everything builds, but just compile one object - copy, compile another - copy. Shoudl't it be like that : compile evrything and copy then ?

Also interesting, how "clib2.lha" is created ? Is it the same "overwrite" things in the SDK, and then from that place craated an archive ?

> If you change the path in the makefile to point to your SDK everything will be ok.
> So maybe we can test against SDK or PREFIX. What do you think?

I replaced it on:

```
INSTALL_PREFIX = /usr/local/amiga/ppc-amigaos/SDK/clib2
SDK_INCLUDE := /usr/local/amiga/ppc-amigaos/SDK/include
```

and then run ```make -f GNUmakefile.os4``` and have that:


```
user@DESKTOP-3NFAB0O /amiga2/clib2-master
$ make -f GNUmakefile.os4
Assembling \033[0;33m[build/lib]\033[0m \r\t\t\t\t\t\t\t\t \033[0;31mcrt0.o\033[0m
cp -r ./build/lib/crt0.o /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/
Compiling Static \033[0;33m[build/lib]\033[0m \r\t\t\t\t\t\t\t\t \033[0;31mcrtbegin.o\033[0m
cp -r ./build/lib/crtbegin.o /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/
Compiling Static \033[0;33m[build/lib]\033[0m \r\t\t\t\t\t\t\t\t \033[0;31mcrtend.o\033[0m
cp -r ./build/lib/crtend.o /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/
Compiling Static \033[0;33m[build/lib]\033[0m \r\t\t\t\t\t\t\t\t \033[0;31mshcrtbegin.o\033[0m
cp -r ./build/lib/shcrtbegin.o /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/
Compiling Static \033[0;33m[build/lib]\033[0m \r\t\t\t\t\t\t\t\t \033[0;31mshcrtend.o\033[0m
cp -r ./build/lib/shcrtend.o /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/
make: *** No rule to make target 'build/./build/lib/libc.so', needed by 'all-targets'.  Stop.

user@DESKTOP-3NFAB0O /amiga2/clib2-master
$
```

**Comment by kas1e** [comment]
To update ticket so it not lost on forum posts:

There another error : Makefile don't create subdirs automatically. What it mean, is that if you want to install it all to some freshly created directory like "/test", build process fail right from begining , because can't find /test/lib , while, instead of failing, it should just create such a dir if there is none.

As for first error , when created "build/.build" , i assume it's issues in the libc.gmk. At least that the file which do create libc.so ?

**Comment by afxgroup** [comment]
Fixed
