### ISSUE TITLE
sysvipc problems

### ISSUE THREAD

**Issue by kas1e** [afxgroup/clib2#34]
issue #1 : we can't build clib2 without "sysvipc", while in readme it point out that it's optional. Maybe some ifdefs missing ? Because without installing sysvpc we have error about missing proto/sysvipc.h. So or we need to made it to be really optional (add ifdefs where need it , etc), or we need to supply necessary includes together with clib2 maybe ?

issue #2: installing ```http://os4depot.net/share/development/library/misc/sysvipc.lha```  by coping includes to SDK from sysvipc/include/, cause clib2 build to fail, with lots of errors about redefination, like this:

```
$ make -f GNUmakefile.os4 SDK_INCLUDE=/usr/local/amiga/ppc-amigaos/SDK/include INSTALL_PREFIX=/test
INSTALL_PREFIX = /test
SDK_INCLUDE = /usr/local/amiga/ppc-amigaos/SDK/include
BUILD_DIR = /amiga2/clib2-master/build
Compiling Shared [/amiga2/clib2-master/build/obj.shared/libc]                            libc_init_global.o
In file included from /usr/local/amiga/ppc-amigaos/SDK/include/include_h/proto/sysvipc.h:10,
                 from /amiga2/clib2-master/library/stdlib/stdlib_sysvbase.h:16,
                 from /amiga2/clib2-master/library/posix/shm_headers.h:13,
                 from /amiga2/clib2-master/library/libc_init_global.c:22:
/usr/local/amiga/ppc-amigaos/SDK/include/include_h/libraries/sysvipc.h:71:8: error: redefinition of ‘struct ipc_perm’
 struct ipc_perm {
        ^~~~~~~~
In file included from /amiga2/clib2-master/library/posix/shm_headers.h:6,
                 from /amiga2/clib2-master/library/libc_init_global.c:22:
/amiga2/clib2-master/library/include/sys/shm.h:26:8: note: originally defined here
 struct ipc_perm
        ^~~~~~~~
```

and so on for ```struct shmid_ds```, ```msglen_t```, ```msgqnum_t```,```struct msgsnap_head``` and all others.

**Comment by afxgroup** [comment]
fixed
