### ISSUE TITLE
another problem with Makefiles 

### ISSUE THREAD

**Issue by kas1e** [afxgroup/clib2#35]
After fixing some problems with Makefiles we go futher, but there is left one more : Makefile do not create subdirs in the directory which we choose for installation. To reproduce:

-- create directory "/test"
-- run build process like that :  ```make -f GNUmakefile.os4 SDK_INCLUDE=/usr/local/amiga/ppc-amigaos/SDK/include INSTALL_PREFIX=/test```
-- it will fail with words:
```
Assembling [/amiga2/clib2-master/build/lib]                                              crt0.o
cp -r /amiga2/clib2-master/build/lib/crt0.o /test/lib/
cp: cannot create regular file '/test/lib/': Not a directory
make: *** [GNUmakefile.os4:159: /amiga2/clib2-master/build/lib/crt0.o] Error 1
```

To fix it i had manually create directory ```lib``` inside of our ```test``` directory.

IMHO makefile should create necessary subdirectory(s) if they weren't found in the directory on which we point out.

**Comment by afxgroup** [comment]
fixed
