### ISSUE TITLE
clib2 exe cannot be deleted after first run

### ISSUE THREAD

**Issue by afxgroup** [afxgroup/clib2#66]
Some people claim that exe file cannot be deleted after the first run. This is a problem present also on original clib2 but I can't reproduce it on Sam440 and Sam460.
So if someone can reproduce it on X5000 or X1000 please write there...

**Comment by afxgroup** [comment]
I think it is a problem with public elf.library. The next elf.library release should fix the problem

**Comment by 3246251196** [comment]
I also can confirm this. I do not quite yet have the latest elf library. I comment here because you may be able to close the issue if you have 100% confirmed that it is the elf.library that causes the issue...

**Comment by 3246251196** [comment]
Can confirm that the latest elf.library does solve this issue. So you may wan to close this ticket @afxgroup

**Comment by afxgroup** [comment]
ok thanks
