### ISSUE TITLE
putenv() compiled for g++ failed for latest clib2-beta07

### ISSUE THREAD

**Issue by kas1e** [afxgroup/clib2#68]
Found freshly introduced issue (as with older version of clib2 it surely compiles).

Firstly found it for SDL_putenv , then realize this is simple redefine to putenv(), so test case are:

```
#include <stdlib.h>

char env[] = "asdfasdfas";

int main()
{
putenv(env);
}
```

And then:

ppc-amigaos-gcc -mcrt=newlib test.c - compiles fine, no warnings
ppc-amigaos-g++ -mcrt=newlib test.c - compiles fine, no warnings

ppc-amigaos-gcc -mcrt=clib2 test.c - compiles fine, but with warning
ppc-amigaos-g++ -mcrt=clib2 test.c - NOT compiles, and warning now turns to error.

Error (same as warning when we compile via gcc) says "error: ‘putenv’ was not declared in this scope; did you mean ‘setenv’?".  While we definately have putenv() code in clib2.

**Comment by afxgroup** [comment]
Fixed in beta8 however if you read 

https://man7.org/linux/man-pages/man3/putenv.3.html

It seems that putenv needs _XOPEN_SOURCE or _GNU_SOURCE or _BSD_SOURCE before stdlib include.
However the exe is created correctly even if you get only a warning
