### ISSUE TITLE
Possible error at the amigaos.h

### ISSUE THREAD

**Issue by walkero-gr** [afxgroup/clib2#69]
I was looking at the amigaos.h replacement file of yours and I think the following line might be problematic
https://github.com/afxgroup/clib2/blob/beta8/misc/amigaos.h#L202

`-L%(base_gcc)lib/gcc/ppc-amigaos/%(version)/clib2/%(lib_subdir_clib2) \`

I think this should be like

`-L%(base_gcc)lib/gcc/ppc-amigaos/%(version)/clib2/lib%(lib_subdir_type) \`

But I might be wrong as well, but I think it matches better the old line.

**Comment by afxgroup** [comment]
I'll check it. Did you manage to use shared objects?

**Comment by walkero-gr** [comment]
Yeah, probably is right. I compared it only with the old line. I am going to close that issue.

I haven't managed to have a compiled gcc yet, having some errors because of the SDK I am using. I paused it for today because I was working on some pipelines that will be used by this as well. I will work on that again tomorrow.
