### ISSUE TITLE
codecvt and clib2

### ISSUE THREAD

**Issue by seventhwonder-amiga** [afxgroup/clib2#70]
I am trying to compile this codecvt example with clib2
at:
https://en.cppreference.com/w/cpp/locale/codecvt

However the output is 

ppc-amigaos-g++ -mcrt=clib2 -athread=native test.cpp -o codecvt -lpthread -lz
/tmp/cc0nN0eZ.o: In function `_ZNSt7codecvtIDsc10_mbstate_tEC2Ej':
test.cpp:(.text._ZNSt7codecvtIDsc10_mbstate_tEC2Ej[_ZNSt7codecvtIDsc10_mbstate_tEC5Ej]+0x2e): undefined reference to `_ZTVSt7codecvtIDsc10_mbstate_tE'
test.cpp:(.text._ZNSt7codecvtIDsc10_mbstate_tEC2Ej[_ZNSt7codecvtIDsc10_mbstate_tEC5Ej]+0x32): undefined reference to `_ZTVSt7codecvtIDsc10_mbstate_tE'
/tmp/cc0nN0eZ.o: In function `_ZN15deletable_facetISt7codecvtIDsc10_mbstate_tEED2Ev':
test.cpp:(.text._ZN15deletable_facetISt7codecvtIDsc10_mbstate_tEED2Ev[_ZN15deletable_facetISt7codecvtIDsc10_mbstate_tEED5Ev]+0x30): undefined reference to `_ZNSt7codecvtIDsc10_mbstate_tED2Ev'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x10): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE6do_outERS0_PKDsS4_RS4_PcS6_RS6_'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x14): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE10do_unshiftERS0_PcS3_RS3_'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x18): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE5do_inERS0_PKcS4_RS4_PDsS6_RS6_'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x1c): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE11do_encodingEv'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x20): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE16do_always_noconvEv'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x24): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE9do_lengthERS0_PKcS4_j'
/tmp/cc0nN0eZ.o:(.rodata._ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTV15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x28): undefined reference to `_ZNKSt7codecvtIDsc10_mbstate_tE13do_max_lengthEv'
/tmp/cc0nN0eZ.o:(.rodata._ZTI15deletable_facetISt7codecvtIDsc10_mbstate_tEE[_ZTI15deletable_facetISt7codecvtIDsc10_mbstate_tEE]+0x8): undefined reference to `_ZTISt7codecvtIDsc10_mbstate_tE'
collect2: error: ld returned 1 exit status

Kas1e recommended that I have to compile stdc++ with new clib2.

But I guess it is already in the SDK ?

When I check, I can see there is libstdc++.a 24,4 MB at
usr/local/amiga/ppc-amigaos/lib/clib2

**Comment by kas1e** [comment]
I tried to recompile libstdc++ by this:

```
cd /amiga/adtools/

rm -f ./native-build/gcc-cross-done-11.3.0

find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name .la -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name.lo -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name .o -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name.so -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name .a -exec rm -f {} +

rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/.libs/*.*
rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.la
rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.lo
rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.o
rm -f ./native-build/gcc-cross-build-11.3.0/gcc/clib2/*.*

make -C native-build gcc-cross CROSS_PREFIX=/usr/local/amiga/
```

But this error still here ..

**Comment by kas1e** [comment]
@Sinan
As i say on forum you just need to recompile libstdc++ as Andrea says. I check now , and it works with this example. That what you need to do:

```
cd /amiga/adtools/

rm -f ./native-build/gcc-cross-done-11.3.0

find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.la -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.lo -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.o -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.so -exec rm -f {} +
find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.a -exec rm -f {} +

rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/.libs/*.*
rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.la
rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.lo
rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.o
rm -f ./native-build/gcc-cross-build-11.3.0/gcc/clib2/*.*

make -C native-build gcc-cross CROSS_PREFIX=/usr/local/amiga/
```

And that all. At least your test case surely compiles after this.

**Comment by sinan** [comment]
I don't think I need to do that @kas1e, I think you need to tag the right Sinan 😁

**Comment by kas1e** [comment]
@sinan 
Ops ! Sorry :)

**Comment by seventhwonder-amiga** [comment]
> @sinan As i say on forum you just need to recompile libstdc++ as Andrea says. I check now , and it works with this example. That what you need to do:
> 
> ```
> cd /amiga/adtools/
> 
> rm -f ./native-build/gcc-cross-done-11.3.0
> 
> find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.la -exec rm -f {} +
> find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.lo -exec rm -f {} +
> find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.o -exec rm -f {} +
> find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.so -exec rm -f {} +
> find ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2 -name *.a -exec rm -f {} +
> 
> rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/.libs/*.*
> rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.la
> rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.lo
> rm -f ./native-build/gcc-cross-build-11.3.0/ppc-amigaos/clib2/libstdc++-v3/src/*.o
> rm -f ./native-build/gcc-cross-build-11.3.0/gcc/clib2/*.*
> 
> make -C native-build gcc-cross CROSS_PREFIX=/usr/local/amiga/
> ```
> 
> And that all. At least your test case surely compiles after this.

Thanks... 
Yes the test case is compiling now.

**Comment by afxgroup** [comment]
Good to know. I'll add a wiki page. Unfortunately if clib2 is not released along SDK you will have gcc libraries compiled with original clib2
