### ISSUE TITLE
libauto.a missing

### ISSUE THREAD

**Issue by kas1e** [afxgroup/clib2#74]
Checked latest release archive (beta7), and there is no libauto.a included. I remember i create such report in April, and we add it, but i checked all released betas, and none of them have libauto.a inside. Is it intendent that we do not have libauto in clib2 anymore, or not included by mistake ?

**Comment by afxgroup** [comment]
It is not missing. It is in beta8 that is the branch you have to use at moment

**Comment by afxgroup** [comment]
Fixed
